### ISSUE TITLE
не обрабатываются сообщения

### ISSUE THREAD

**Issue by smartmanru** [SlavikMIPT/opentfd#5]
Не обрабатываются сообщения состоящие из " ` " , также при большом кол-ве сообщений (до 3 в секунду) обрабатывается только 2

**Comment by SlavikMIPT** [comment]
" ` " - символ markdown разметки ```code```, размеченный текст не обрабатывается

**Comment by SlavikMIPT** [comment]
по большой частоте сообщений - нужно очередь использовать, заодно и задержку на склеивание сообщений добавить и редактировать последнее сообщение вместо первого, чтобы чат не прыгал
